#!/usr/bin/env bash

set -e

ACTION=$1

case "$ACTION" in
attache)
  docker attach "${*:2}"
  ;;

construis)
  docker build "${*:2}"
  ;;

engage)
  docker commit "${*:2}"
  ;;

copie)
  docker cp "${*:2}"
  ;;

crée)
  docker create "${*:2}"
  ;;

changements)
  docker diff "${*:2}"
  ;;

événements|évènements)
  docker events "${*:2}"
  ;;

réalise)
	docker exec "${*:2}"
	;;

exporte)
	docker export "${*:2}"
	;;

historique)
	docker history "${*:2}"
	;;

images)
	docker images "${*:2}"
	;;

importe)
	docker import "${*:2}"
	;;

info)
	docker info "${*:2}"
	;;

inspecte)
	docker inspect "${*:2}"
	;;

tue)
	docker kill "${*:2}"
	;;

charge)
	docker load "${*:2}"
	;;

connecte)
	docker login "${*:2}"
	;;

déconnecte)
	docker logout "${*:2}"
	;;

journal)
	docker logs "${*:2}"
	;;

réseau)
	docker network "${*:2}"
	;;

bloque)
	docker pause "${*:2}"
	;;

port)
	docker port "${*:2}"
	;;

liste)
	docker ps "${*:2}"
	;;

récupère)
	docker pull "${*:2}"
	;;

publie)
	docker push "${*:2}"
	;;

renomme)
	docker rename "${*:2}"
	;;

redémarre)
	docker restart "${*:2}"
	;;

suppr)
	docker rm "${*:2}"
	;;

sim)
	docker rmi "${*:2}"
	;;

actionne)
	docker run "${*:2}"
	;;

suvegarde)
	docker save "${*:2}"
	;;

recherche)
	docker search "${*:2}"
	;;

démarre)
	docker start "${*:2}"
	;;

stats)
	docker stats "${*:2}"
	;;

arrête)
	docker stop "${*:2}"
	;;

labellise)
	docker tag "${*:2}"
	;;

premiers)
	docker top "${*:2}"
	;;

débloque)
	docker unpause "${*:2}"
	;;

version)
	docker version "${*:2}"
	;;

tome)
	docker volume "${*:2}"
	;;

attend)
	docker wait "${*:2}"
	;;
esac
